[[protocols]]
name = "sony12"
protocol = "sony12"
variant = "sony12"
[protocols.scancodes]
0x10025 = "KEY_INPUT_SRC"
0x10015 = "KEY_POWER"
0x10000 = "KEY_1"
0x10001 = "KEY_2"
0x10002 = "KEY_3"
0x10003 = "KEY_4"
0x10004 = "KEY_5"
0x10005 = "KEY_6"
0x10006 = "KEY_7"
0x10007 = "KEY_8"
0x10008 = "KEY_9"
0x10009 = "KEY_0"
0x10063 = "KEY_EXIT"
0x1003f = "KEY_MENU"
0x1003a = "KEY_I_PLUS"
0x10060 = "KEY_HOME"
0x10013 = "KEY_VOLUMEDOWN"
0x10012 = "KEY_VOLUMEUP"
0x10010 = "KEY_PROGRAMUP"
0x10011 = "KEY_PROGRAMDOWN"
0x10014 = "KEY_MUTE"
0x1003b = "KEY_LOOP"
0x10017 = "KEY_AUDIO"
0x10034 = "KEY_LEFT"
0x10033 = "KEY_RIGHT"
0x10074 = "KEY_UP"
0x10075 = "KEY_DOWN"
0x10065 = "KEY_OK"

[[protocols]]
name = "sony15"
protocol = "sony15"
variant = "sony15"
[protocols.scancodes]
0x1a007e = "KEY_SEARCH"
0x77000d = "KEY_DIGITAL_ANALOG"
0x1a0057 = "KEY_TV_RADIO"
0x970025 = "KEY_RED"
0x970026 = "KEY_GREEN"
0x970027 = "KEY_YELLOW"
0x970024 = "KEY_PURPLE"
0x1a007c = "KEY_NETFLIX"
0x1a007b = "KEY_QUESTIONMARK"
0x1a0073 = "KEY_DISCOVER"
0x1a007d = "KEY_SEN"
0x970023 = "KEY_RETURN"
0x970036 = "KEY_OPTIONS"
0xa4005b = "KEY_GUIDE"
0x970028 = "KEY_DOTS"
0x1a0074 = "KEY_SOCIALVIEW"
0x97001b = "KEY_REWIND"
0x97001a = "KEY_PLAY"
0x97001c = "KEY_FORWARD"
0x970020 = "KEY_REC"
0x970019 = "KEY_PAUSE"
0x970018 = "KEY_STOP"
0x1a0058 = "KEY_SYNCMENU"
0x1a0067 = "KEY_TVPAUSE"
0x1a0076 = "KEY_FOOTBALL"

