[[protocols]]
name = "custom_protocol"
protocol = "rc5"
variant = "rc5"
[protocols.scancodes]
0x140c = "KEY_POWER"
0x100c = "KEY_AMP_POWER"
0x113f0a = "KEY_TUNER"
0x1120 = "KEY_TUNERUP"
0x1121 = "KEY_TUNERDOWN"
0x143f = "KEY_CD"
0x1a3f = "KEY_RECORDER"
0x193f0a = "KEY_NETWORK"
0x153f = "KEY_PHONO"
0x100119 = "KEY_COAXIAL"
0x10011a = "KEY_OPTICAL"
0x1421 = "KEY_FASTREWIND"
0x1420 = "KEY_FASTFORWARD"
0x1442 = "KEY_SOUNDMODE"
0x1436 = "KEY_STOP"
0x1435 = "KEY_PLAY"
0x1430 = "KEY_PAUSE"
0x143f0e = "KEY_INPUT"
0x140f0a = "KEY_INFO"
0x1022 = "KEY_SOURCEDIRECT"
0x100d = "KEY_MUTE"
0x1010 = "KEY_VOLUMEUP"
0x1011 = "KEY_VOLUMEDOWN"
0x140b = "KEY_TIME"
0x14760d = "KEY_MODE"
0x1450 = "KEY_UP"
0x1455 = "KEY_LEFT"
0x1456 = "KEY_RIGHT"
0x1451 = "KEY_DOWN"
0x1457 = "KEY_ENTER"
0x1429 = "KEY_PROG"
0x1452 = "KEY_MENU"
0x1401 = "KEY_1"
0x1402 = "KEY_2"
0x1403 = "KEY_3"
0x1404 = "KEY_4"
0x1405 = "KEY_5"
0x1406 = "KEY_6"
0x1407 = "KEY_7"
0x1408 = "KEY_8"
0x1409 = "KEY_9"
0x14000a = "KEY_10"
0x1400 = "KEY_0"
0x1431 = "KEY_CLEAR"
0x1447 = "KEY_DIMMER"
0x141c = "KEY_RANDOM"
0x141d = "KEY_REPEAT"
0x143b = "KEY_AB"
